version: "3"
services:
  minecraft-mapper-api:
    image: robgray/minecraft-mapper-api:latest
    network_mode: "bridge"
    restart: unless-stopped
    ports:
      - 9000:80
    environment:
      - ConsoleLogging=true

  minecraft-mapper-ui:
    image: robgray/minecraft-mapper-ui:latest
    network_mode: "bridge"
    restart: unless-stopped
    volumes:
      - /app/nodemodules
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true