version: "3.8"
services:

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=str@ngP@ssw@rd
    ports:
      - "1433:1433"
    volumes:
      - C:/DockerLinux/Volumes/MinecraftMapper/SqlServer:/var/opt/mssql/data
    
  seq:
    image: datalust/seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"
    volumes:
      - C:/DockerLinux/Volumes/PhysioAgent/Seq:/data
      
  azure-storage:
    ports:
      - '10000:10000'
      - '10001:10001'
    image: mcr.microsoft.com/azure-storage/azurite.